import turtle
turtle.left(90)
turtle.forward(185)
turtle.right(90)
turtle.penup()
turtle.forward(90)
turtle.pendown()
turtle.forward(90)
turtle.right(90)
turtle.forward(90)
turtle.right(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.left(90)
turtle.forward(90)
turtle.penup()
turtle.forward(90)
turtle.pendown()
for i in range(0,4):
    turtle.forward(90)
    turtle.left(90)
for i in range(0,1):
    turtle.forward(90)
    turtle.left(90)
for i in range(0,2):
    turtle.forward(90)
for i in range(0,2):
    turtle.left(90)
    turtle.forward(90)
turtle.hideturtle()
turtle.exitonclick()